version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:9.4.12-alpine
    steps:
      - checkout

      - type: cache-restore
        key: v1-rails-demo-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      - type: cache-save
        key: v1-rails-demo-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run:
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load

      - run: bundle exec rspec
